# Generated by Django 5.2 on 2025-05-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="chat_files/"),
        ),
    ]
