# Generated by Django 5.2 on 2025-05-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_message_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="groupchat_files/"),
        ),
    ]
